//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LekplatsService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lekplatser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lekplatser()
        {
            this.IndividuellaBetyg = new HashSet<IndividuellaBetyg>();
            this.Lekutrustning = new HashSet<Lekutrustning>();
            this.Tillgänglighet = new HashSet<Tillgänglighet>();
        }
    
        public int LekplatsId { get; set; }
        public string Namn { get; set; }
        public string Adress { get; set; }
        public string Beskrivning { get; set; }
        public Nullable<byte> MinÅlderMålgrupp { get; set; }
        public Nullable<byte> MaxÅlderMålgrupp { get; set; }
        public int FK_Områden_OmrådeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividuellaBetyg> IndividuellaBetyg { get; set; }
        public virtual Områden Områden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lekutrustning> Lekutrustning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tillgänglighet> Tillgänglighet { get; set; }
    }
}
