//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LekplatsService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabasLekplatserEntities : DbContext
    {
        public DatabasLekplatserEntities()
            : base("name=DatabasLekplatserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IndividuellaBetyg> IndividuellaBetyg { get; set; }
        public virtual DbSet<Lekplatser> Lekplatser { get; set; }
        public virtual DbSet<Lekutrustning> Lekutrustning { get; set; }
        public virtual DbSet<Områden> Områden { get; set; }
        public virtual DbSet<Tillgänglighet> Tillgänglighet { get; set; }
    }
}
