//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LekplatsService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lekutrustning
    {
        public int LekutrustningId { get; set; }
        public int Ordning { get; set; }
        public string Beskrivning { get; set; }
        public int FK_Lekplatser_LekplatsId { get; set; }
    
        public virtual Lekplatser Lekplatser { get; set; }
    }
}
